title:              Ji Won Park
email:              jwp@stanford.edu
description:        Ph.D. student at Stanford, probabilistic ML x astrophysics
author:             Ji Won Park
baseurl:            ""
url:                "https://jiwoncpark.github.io"

# Social Profiles
twitter_username: jiwoncpark
github_username: jiwoncpark
facebook_username:
instagram_username:  
linkedin_username: ji-won-park
cv_url: https://drive.google.com/file/d/1aZRrBrzzGgYHjSja_IicCxKg6hC2JaOe/view?usp=sharing
google_scholar_url: https://scholar.google.com/citations?user=URG3MMYAAAAJ&hl=en

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-R7D27X1GF2 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
